//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD3
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIN_R1DzHbCu6sngUGQKCMVXuQ___0
    {
        public decimal ID_FRECUENCIA { get; set; }
        public string DESCRIPCION { get; set; }
    }
}
