//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD3
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGR_LABORATORIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SGR_LABORATORIOS()
        {
            this.SGR_LABS_CIIU_TARIFA = new HashSet<SGR_LABS_CIIU_TARIFA>();
            this.SGR_LABS_LOC_MUEST = new HashSet<SGR_LABS_LOC_MUEST>();
            this.SGR_MUESTREADORES = new HashSet<SGR_MUESTREADORES>();
        }
    
        public decimal ID_LABORATORIO { get; set; }
        public string RUT { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string GIRO { get; set; }
        public decimal ID_LOCALIDAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGR_LABS_CIIU_TARIFA> SGR_LABS_CIIU_TARIFA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGR_LABS_LOC_MUEST> SGR_LABS_LOC_MUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGR_MUESTREADORES> SGR_MUESTREADORES { get; set; }
    }
}
