//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD3
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGR_LABS_LOC_MUEST
    {
        public decimal ID_LABORATORIO { get; set; }
        public decimal ID_LOCALIDAD { get; set; }
        public string ID_TIPO_MUESTRA { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public decimal ACTIVO { get; set; }
    
        public virtual SGR_LABORATORIOS SGR_LABORATORIOS { get; set; }
        public virtual SGR_LOCALIDADES SGR_LOCALIDADES { get; set; }
    }
}
