//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD3
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGR_EMPRESAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SGR_EMPRESAS()
        {
            this.SGR_CLIENTES = new HashSet<SGR_CLIENTES>();
            this.SGR_FISCALIZADORES = new HashSet<SGR_FISCALIZADORES>();
            this.SGR_PLANTAS = new HashSet<SGR_PLANTAS>();
            this.SGR_USUARIOS = new HashSet<SGR_USUARIOS>();
        }
    
        public decimal ID_EMPRESA { get; set; }
        public Nullable<decimal> ID_REGION { get; set; }
        public string NOMBRE_EMPRESA { get; set; }
        public string RUT_EMPRESA { get; set; }
        public decimal ACTIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGR_CLIENTES> SGR_CLIENTES { get; set; }
        public virtual SGR_REGIONES SGR_REGIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGR_FISCALIZADORES> SGR_FISCALIZADORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGR_PLANTAS> SGR_PLANTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGR_USUARIOS> SGR_USUARIOS { get; set; }
    }
}
