//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD3
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGR_PARAMETROS_RILES
    {
        public decimal ID_PARAMETRO_RILES { get; set; }
        public string CODIGO_LIMS { get; set; }
        public string SIGLA_SGR { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> V_MINIMO { get; set; }
        public Nullable<decimal> V_MAXIMO { get; set; }
        public decimal ACTIVO { get; set; }
        public string UNIDAD_MEDIDA { get; set; }
    }
}
