//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD3
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGR_CLIENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SGR_CLIENTES()
        {
            this.SGR_UNIDADES_DESCARGA = new HashSet<SGR_UNIDADES_DESCARGA>();
            this.SGR_SERVICIOS = new HashSet<SGR_SERVICIOS>();
        }
    
        public decimal ID_SGR { get; set; }
        public Nullable<decimal> ID_RUBRO { get; set; }
        public Nullable<decimal> ID_EMPRESA { get; set; }
        public string RUT_CLIENTE { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string REP_LEGAL { get; set; }
        public string RUT_REP_LEGAL { get; set; }
        public string DV_REP_LEGAL { get; set; }
        public Nullable<decimal> ID_SISS { get; set; }
        public Nullable<decimal> ID_PLANTA { get; set; }
        public string NOMBRE_FANTASIA { get; set; }
        public Nullable<decimal> ID_TIPO_CLIENTE { get; set; }
        public Nullable<decimal> ID_ESTADO_CLIENTE { get; set; }
        public Nullable<decimal> ID_COMUNA { get; set; }
        public Nullable<decimal> ID_CONTRATO { get; set; }
        public Nullable<decimal> ID_TIPO_CALCULO { get; set; }
        public string DIRECCION { get; set; }
        public string SECTOR { get; set; }
        public Nullable<decimal> FONO { get; set; }
        public Nullable<decimal> FAX { get; set; }
        public string CASILLA_POSTAL { get; set; }
        public string CODIGO_POSTAL { get; set; }
        public string CONTACTO1 { get; set; }
        public string RUT_CONTACTO1 { get; set; }
        public string EMAIL_CONTACTO1 { get; set; }
        public Nullable<decimal> FONO_CONTACTO1 { get; set; }
        public string CONTACTO2 { get; set; }
        public string RUT_CONTACTO2 { get; set; }
        public string EMAIL_CONTACTO2 { get; set; }
        public Nullable<decimal> FONO_CONTACTO2 { get; set; }
        public string CONTACTO_RILES { get; set; }
        public string RUT_CONTACTO_RILES { get; set; }
        public string EMAIL_CONTACTO_RILES { get; set; }
        public Nullable<decimal> FONO_CONTACTO_RILES { get; set; }
        public string IDENT_CONCES_DGA_RILES { get; set; }
        public Nullable<decimal> NRO_RCA { get; set; }
        public Nullable<decimal> ANO_RCA { get; set; }
        public string CONV_DGA_DSMOP { get; set; }
        public Nullable<decimal> ID_TIPO_SIST_TRATAMI { get; set; }
        public Nullable<System.DateTime> FECHA_ENT_OPER_RILES { get; set; }
        public Nullable<decimal> VOLUMEN_DESCARGA { get; set; }
        public Nullable<decimal> NRO_DESCARGAS { get; set; }
        public Nullable<decimal> RPM { get; set; }
        public Nullable<decimal> NRO_RPM { get; set; }
        public Nullable<decimal> ID_FREC_MUESTREO { get; set; }
        public string LINK_RPM { get; set; }
        public Nullable<System.DateTime> FECHA_T4_RPM { get; set; }
        public Nullable<decimal> ID_CON_DIRECTO { get; set; }
        public Nullable<decimal> ID_CON_CONVENIO { get; set; }
        public Nullable<decimal> ID_CON_OPERATIVO { get; set; }
        public Nullable<decimal> ID_EXCEDENTES { get; set; }
        public Nullable<decimal> ID_DGA_RILES { get; set; }
        public Nullable<decimal> ID_DGA_AS { get; set; }
        public Nullable<decimal> ID_DGA_RESIDUOS { get; set; }
        public Nullable<decimal> CAMPO_F_1 { get; set; }
        public Nullable<decimal> CAMPO_F_2 { get; set; }
        public Nullable<decimal> CAMPO_F_3 { get; set; }
        public Nullable<decimal> CAMPO_F_4 { get; set; }
        public Nullable<decimal> CAMPO_F_5 { get; set; }
        public string GIRO { get; set; }
        public string RAZON_SOCIAL { get; set; }
    
        public virtual SGR_PLANTAS SGR_PLANTAS { get; set; }
        public virtual SGR_EMPRESAS SGR_EMPRESAS { get; set; }
        public virtual SGR_COMUNAS SGR_COMUNAS { get; set; }
        public virtual SGR_TIPOS_CLIENTE SGR_TIPOS_CLIENTE { get; set; }
        public virtual SGR_ESTADOS_CLIENTE SGR_ESTADOS_CLIENTE { get; set; }
        public virtual SGR_TIPOS_CALC_EXC SGR_TIPOS_CALC_EXC { get; set; }
        public virtual SGR_TIPOS_SIST_TRAT SGR_TIPOS_SIST_TRAT { get; set; }
        public virtual SGR_FRECUENCIAS_MUES SGR_FRECUENCIAS_MUES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGR_UNIDADES_DESCARGA> SGR_UNIDADES_DESCARGA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGR_SERVICIOS> SGR_SERVICIOS { get; set; }
    }
}
