//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD3
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGR_UNIDADES_DESCARGA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SGR_UNIDADES_DESCARGA()
        {
            this.SGR_SERVICIOS_UDS = new HashSet<SGR_SERVICIOS_UDS>();
        }
    
        public decimal ID_UD { get; set; }
        public Nullable<decimal> COD_SGC_UD { get; set; }
        public Nullable<decimal> ID_SGR { get; set; }
        public Nullable<decimal> COD_COLECTOR { get; set; }
        public Nullable<decimal> COD_CIIU { get; set; }
        public Nullable<decimal> UTM_NORTE_UD { get; set; }
        public Nullable<decimal> UTM_ESTE_UD { get; set; }
    
        public virtual SGR_CLIENTES SGR_CLIENTES { get; set; }
        public virtual SGR_CODIGOS_CIIU SGR_CODIGOS_CIIU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGR_SERVICIOS_UDS> SGR_SERVICIOS_UDS { get; set; }
    }
}
