//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD3
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGR_SERVICIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SGR_SERVICIOS()
        {
            this.SGR_SERVICIOS_UDS = new HashSet<SGR_SERVICIOS_UDS>();
        }
    
        public decimal ID_SERVICIO { get; set; }
        public string RUT_EMPRESA { get; set; }
        public Nullable<decimal> TIPO_SERVICIO { get; set; }
        public Nullable<decimal> ID_SGR { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<decimal> VOLUMEN_DM { get; set; }
        public string ESTADO { get; set; }
        public string LOCALIDAD { get; set; }
        public Nullable<decimal> TIPO_FACTURACION { get; set; }
        public Nullable<decimal> CONVENIO { get; set; }
        public Nullable<System.DateTime> FECHA_FACTURACION { get; set; }
    
        public virtual SGR_CLIENTES SGR_CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGR_SERVICIOS_UDS> SGR_SERVICIOS_UDS { get; set; }
    }
}
