//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD3
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGR_FISCALIZADORES
    {
        public decimal ID_FISCALIZADOR { get; set; }
        public string RUT { get; set; }
        public string NOMBRE { get; set; }
        public decimal ID_EMPRESA { get; set; }
        public decimal ACTIVO { get; set; }
    
        public virtual SGR_EMPRESAS SGR_EMPRESAS { get; set; }
    }
}
