//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD3
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGR_SERVICIOS_UDS
    {
        public decimal ID_SERVICIO { get; set; }
        public decimal ID_UD { get; set; }
        public decimal PORCENTAJE { get; set; }
    
        public virtual SGR_SERVICIOS SGR_SERVICIOS { get; set; }
        public virtual SGR_UNIDADES_DESCARGA SGR_UNIDADES_DESCARGA { get; set; }
    }
}
